# -*- coding: utf-8 -*-
"""
把高德地图截图压缩成 Base64，写进 prototype-figma/code.js 末尾。

为什么需要它（2026-08-24，依用户反馈「否则每次都要替换很麻烦」）：
原型里地图底板共 9 个落点（mapCanvas 8 处 + buildMapSelector 1 处），
过去每次重跑插件都得在 Figma 里手工贴 9 次图。
Figma 官方 API figma.base64Decode + figma.createImage 支持把图片
以 Base64 形式随插件代码分发，无需任何网络请求，故改为内嵌。

用法：在仓库根目录执行 python tools/embed-map-bg.py
效果：覆写 code.js 末尾由哨兵注释界定的常量段，可反复执行不会堆叠。
"""
import base64
import io
import os

from PIL import Image

SRC = os.path.join('docs', 'map-bg.png')
DST = os.path.join('prototype-figma', 'code.js')

# 常量段的起止哨兵。按哨兵定位而非按行号或变量名正则，
# 这样 code.js 前面的逻辑代码怎么改都不影响本脚本定位的准确性。
BEGIN = '// >>> MAP_BG_ASSET_BEGIN (generated by tools/embed-map-bg.py, do not edit by hand)'
END = '// <<< MAP_BG_ASSET_END'

# 目标尺寸 = 地图区 390x688 的 2 倍。
# 选 2x 而非 1x：Figma 画布常在 100%~200% 之间评审，1x 图放大后路名会糊。
# 选 q70 而非 q80：实测 q70 = 174.3KB / q80 = 216.7KB 的 Base64，肉眼差异极小。
TARGET_W, TARGET_H = 780, 1376
QUALITY = 70

TEMPLATE = """{begin}
// ============================================================
// 附：地图底图内嵌资产
//
// 一张高德地图截图（合肥京商商贸城一带，约 1-2km 视野），
// 经 tools/embed-map-bg.py 裁切压缩为 {w}x{h} JPEG q{q} 后做 Base64 编码。
//
// 为什么内嵌而不留空位人工贴图：底板共 9 个落点，
// 每次重跑插件都要手工贴 9 次，纯属重复劳动且容易漏贴。
// Figma 官方文档《Working with Images》明确支持以 Base64 形式随插件分发图片，
// 不产生任何网络请求，故 manifest 的 networkAccess: none 无需放开。
//
// 为什么先在本地裁成 390:688 再编码，而不是把整张原图丢给 Figma 的 FILL 去裁：
// 原图接近正方形，FILL 到竖长的地图区会自行裁掉约 41% 的横向像素，
// 那部分字节等于白编码了。本地裁好可省下这笔开销。
//
// 为什么放在文件末尾：这一大段常量不该挤在逻辑代码中间干扰阅读与 diff。
// var 声明在模块顶层，插件加载时整份脚本已执行完毕，
// 而批次逻辑要到 figma.ui.onmessage 触发时才读它，取值一定已就绪。
//
// 为什么是一整行不折行：整串约 17.4 万字符，折成多行 join 反而让 diff 变成
// 十几行齐变；单行的话换底图只体现为一行差异。
//
// 换底图的办法：替换 docs/map-bg.png 后重跑 python tools/embed-map-bg.py，
// 本段会被整段覆盖，不必手工改这串字符。
//
// 截图仅用于内部评审，须保留高德版权水印，不要去水印后外发。
// ============================================================
var MAP_BG_JPEG_B64 = '{b64}';
{end}
"""


def crop_to_ratio(img, target_w, target_h):
    """把图片按目标宽高比做「最大填充」缩放后中心裁切。

    先按较大的缩放比缩放，保证两边都不小于目标尺寸，再从中心裁掉多余部分，
    这样既不留白也不变形。

    :param img: PIL.Image 源图
    :param target_w: int 目标宽（像素）
    :param target_h: int 目标高（像素）
    :return: PIL.Image 尺寸恰为 target_w x target_h 的新图
    """
    scale = max(target_w / img.width, target_h / img.height)
    img = img.resize((int(round(img.width * scale)), int(round(img.height * scale))), Image.LANCZOS)
    left = (img.width - target_w) // 2
    top = (img.height - target_h) // 2
    return img.crop((left, top, left + target_w, top + target_h))


def encode_jpeg_base64(img, quality):
    """把图片编码为 JPEG 再转 Base64 字符串。

    用 JPEG 而非 PNG：实测这张图有 24740 种颜色，PNG 调色板量化后
    体积反而是 JPEG 的两倍以上。Figma createImage 接受 PNG/JPG/GIF，JPEG 合规。

    :param img: PIL.Image 待编码图片
    :param quality: int JPEG 质量 1-95
    :return: str 不含 data URI 前缀的纯 Base64 字符串
    """
    buf = io.BytesIO()
    img.convert('RGB').save(buf, format='JPEG', quality=quality, optimize=True)
    print('jpeg: %.1f KB' % (len(buf.getvalue()) / 1024.0))
    return base64.b64encode(buf.getvalue()).decode('ascii')


def main():
    """脚本入口：读源图 → 裁切 → 编码 → 覆写 code.js 的底图常量段。

    :return: None
    """
    img = Image.open(SRC)
    print('source: %s %s %s' % (SRC, img.size, img.mode))
    b64 = encode_jpeg_base64(crop_to_ratio(img, TARGET_W, TARGET_H), QUALITY)
    print('base64: %.1f KB' % (len(b64) / 1024.0))

    # newline='' 关闭 Python 的换行符自动转换，读写都保持 code.js 原有的 CRLF，
    # 否则整份文件会被改成另一种行尾、在 git diff 里显示为「每一行都变了」
    with open(DST, 'r', encoding='utf-8', newline='') as f:
        source = f.read()
    newline = '\r\n' if '\r\n' in source else '\n'
    section = TEMPLATE.format(begin=BEGIN, end=END, w=TARGET_W, h=TARGET_H, q=QUALITY, b64=b64)
    if newline == '\r\n':
        section = section.replace('\n', '\r\n')

    begin_at = source.find(BEGIN)
    if begin_at == -1:
        merged = source.rstrip('\r\n') + newline * 2 + section
    else:
        end_at = source.find(END, begin_at)
        if end_at == -1:
            raise RuntimeError('found BEGIN sentinel but no END sentinel in %s' % DST)
        merged = source[:begin_at] + section + source[end_at + len(END):].lstrip('\r\n')

    with open(DST, 'w', encoding='utf-8', newline='') as f:
        f.write(merged)
    print('written: %s (%.1f KB)' % (DST, os.path.getsize(DST) / 1024.0))


if __name__ == '__main__':
    main()
